### ISSUE TITLE
Duplicate, user error

### ISSUE THREAD

**Issue by kpeter1994** [kpeter1994/cubix_software_sft#23]
Ha olyan felhasználónevet akarok regisztrálni, ami már egyszer regisztrálva lett, akkor INTERNAL SERVER ERROR -al tér vissza.

**Comment by FPeterL** [comment]
Hiba rekreálva, detektálva.
A probléma a routeban, a respons lekérésénél volt. Ha a response objektumként jött vissza, akkor is jsonifyztünk. Ezt most vizsgálja és csak akkor alakítja át, ha a response dict.
    user = AuthController().register(username, password, name)
    return jsonify(user), 201 ->
    
        if isinstance(response, dict):
        return jsonify(response), 201
    return response

Tesztelve, most már ha foglalt a user, akkor a jó a response:
 {
	"error": "A felhasználónév már foglalt"
}
