### ISSUE TITLE
Részvényekkel kapcsolatos API funkciók

### ISSUE THREAD

**Issue by kpeter1994** [kpeter1994/cubix_software_sft#32]
- [x] Porfilió visszaadása, ami tartalmazza a részvény bekerülési értékét, az aktuális árfolyamát és a változást %-ban megadva.
- [x] Egy részvény aktuális árának lekérése
- [x] Keresés név és szimbolum alapján a részvények között

**Comment by FPeterL** [comment]
portfolió visszadás kész
`stock/get-portfolio-details?portfolio_id=1`
Válasz:
```
{
	"details": [
		{
			"change_percentage": 70.11,
			"cost_value": "150.25",
			"current_price": 255.58999633789062,
			"quantity": 10,
			"share_id": "AAPL"
		},
		{
			"change_percentage": 29.14,
			"cost_value": "150.25",
			"current_price": 194.0399932861328,
			"quantity": 10,
			"share_id": "GOOG"
		}
	],
	"portfolio_id": 4,
	"portfolio_name": "Teszt portfolio"
}
```
api-tester és wiki frissítve.

**Comment by FPeterL** [comment]
Részvény aktuális árának lekérdezése symbol alapján kész.
`stock/current-price?stock_symbol=GOOG`

```
{
	"current_price": 194.0399932861328,
	"stock_symbol": "GOOG"
}
```

api-tester és wiki frissítve

**Comment by FPeterL** [comment]
Keresés név és szimbolum alapján a részvények között kész.
portfolio.db-be új tábla rögzítve, companies, nincs api lekérdezés cég névre, így manuális lista kellett a lekérdezéshez.
`/stock/search?query=tesla`

`/stock/search?query=tsla`

```
{
	"currency": "USD",
	"market_price": 454.13,
	"name": "Tesla, Inc.",
	"sector": "Consumer Cyclical",
	"symbol": "TSLA"
}
```

új model létrehozva, api-tester frissítve, wiki frissítve, adatbázis frissítve
